- hosts: localhost
  pre_tasks:
    - import_tasks: tasks/update-system.yml
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/update-ansible-repo-origin.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/terminal-apps.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/core-packages.yml
  #   - import_tasks: tasks/qbittorrent.yml
  #   - import_tasks: tasks/syncthing.yml
