- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - git
        - gh-cli
        - dotfiles
        - zsh
        - tmux
        - fzf
        - node
  tasks:
    - include: tasks/homebrew.yml
      when:
        - ansible_facts['os_family']== "Darwin"
    - include: tasks/git.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/fzf.yml
    - include: tasks/node.yml
