- name: Install Google Chrome
  become: true
  tags: 
    - chrome
  community.general.flatpak:
    name: 
      - com.google.Chrome
    state: present
    
- name: Install Brave
  become: true
  tags: 
    - brave
  community.general.flatpak:
    name: 
      - com.brave.Browser
    state: present

- name: Install Proton VPN
  become: true
  tags: 
    - protonvpn
  community.general.flatpak:
    name: 
      - com.protonvpn.www
    state: present

# - name: Install 1Password
#   become: true
#   tags: 
#     - 1password
#   community.general.flatpak:
#     name: 
#       - https://downloads.1password.com/linux/flatpak/1Password.flatpakref
#     state: present

- name: Install Obsidian
  become: true
  tags: 
    - obsidian
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
    state: present

- name: Install Arch specific packages
  become: true
  package:
    name:
      - timeshift
      - timeshift-autosnap
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Install GNUCash 
  become: true
  tags: 
    - gnucash
  community.general.flatpak:
    name: 
      - org.gnucash.GnuCash
    state: present

- name: Install VLC 
  become: true
  tags: 
    - vlc
  community.general.flatpak:
    name: 
      - org.videolan.VLC
    state: present


- name: Install Cryptomator 
  become: true
  tags: 
    - cryptomator
  community.general.flatpak:
    name: 
      - org.cryptomator.Cryptomator
    state: present


- name: Install DBeaver 
  become: true
  tags: 
    - dbeaver
  community.general.flatpak:
    name: 
      - io.dbeaver.DBeaverCommunity
    state: present
