- name: Install base aur packages
  kewlfft.aur.aur:
    name:
      - 1password
      - obsidian-appimage
      - timeshift
      - timeshift-autosnap
      - google-chrome
      - protonvpn
      - nasc
      - guake
      - postman-bin
      - catppuccin-gtk-theme-mocha
      - brave-bin
      - tidal-hifi-bin
      - jellyfin
      - another-redis-desktop-manager-appimage
      - cryptomator-bin

- name: Install community packages
  pacman:
    name:
      - kitty
      - neovim
      - fzf
      - meld
      - xclip
      - ripgrep
      - fd
      - papirus-icon-theme
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-2048-em-mono
      - ttf-nerd-fonts-symbols-2048-em
      - ttf-jetbrains-mono
      - dbeaver
      - vlc
      - noto-fonts-emoji
      - gparted
      - discord
      - gnucash
      - jq
      - lazygit
      - pnpm
      - syncthing
  become: true
