- name: Install base packages
  become: true
  package:
    name:
      - 1password
      - obsidian-appimage
      - timeshift
      - timeshift-autosnap
      - google-chrome
      - protonvpn
      # - postman-bin
      # - brave-bin
      # - tidal-hifi-bin
      # - cryptomator-bin
      # - postman
      # - brave
      # - tidal-hifi
      # - cryptomator
      - another-redis-desktop-manager-appimage
      - alacritty
      - neovim
      - fzf
      - ripgrep
      - fd
      - dbeaver
      - vlc
      - gnucash
      - jq
      - lazygit
      - pnpm
    # name: 1password
    state: present
