- name: Install docker-compose (used by podman)
  become: true
  tags:
    - podman
  package:
    name:
      - docker-compose
    state: latest

- name: Start podman service
  tags:
    - podman
  systemd:
    name: podman.socket
    state: started
    enabled: true
