- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:thomashoggard/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
    version: main


- name: Installing stow
  become: true
  package:
    name: stow
    state: latest

- name: Stow dotfiles
  shell: "cd $HOME/.dotfiles && ./install.sh"

- name: Stow personal dotfiles
  tags: 
    - never
    - personal
  shell: "cd $HOME/.dotfiles && ./install-personal.sh"

- name: Stow work dotfiles
  tags: 
    - never
    - work
  shell: "cd $HOME/.dotfiles && ./install-league.sh"
