# ubuntu
- name: Install fzf
  apt: name=fzf
  when:
    - ansible_facts['os_family'] == "Debian"
  tags: fzf

# arch
- name: Install fzf
  pacman:
    name: fzf
  when:
    - ansible_facts['os_family'] == "Archlinux"
  tags: fzf

# osx
- name: Install fzf
  homebrew:
    name: fzf
  when:
    - ansible_facts['os_family'] == "Darwin"
  tags: fzf
