- name: Install git
  apt: name=git
  tags: git

- name: gh cli archive-keyring.gpg download
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
  tags: gh-cli

- name: gh cli PPA setting
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list
  tags: gh-cli

- name: gh cli apt installation
  become: true
  apt:
    update_cache: yes
    name: gh
  tags: gh-cli
