# Jellyfin installation is untested
- name: Install jellyfin
  become: true
  package:
    name:
      - jellyfin
    state: latest

- name: Start jellyfin service
  systemd:
    name: jellyfin.service
    state: started
    enabled: true

- name: Grant read permissions to media drive
  shell: "setfacl -m user:jellyfin:rxw {{ lookup('env', 'USER') }}"
  become: true
