- name: Install npm
  become: true
  package:
    name: npm
    state: latest

- name: Install pnpm
  become: true
  package:
    name: pnpm
    state: latest

- name: Install n (node package manager)
  become: true
  community.general.npm:
    name: n
    global: true

- name: Install latest version of node using n
  become: true
  shell: "n latest"
