- name: Install qbittorrent
  become: true
  package:
    name: qbittorrent
    state: present

- name: Install jackett
  become: true
  package:
    name: jackett
    state: present

- name: Start jackett service
  systemd:
    name: jackett.service
    state: started
    enabled: true
