- name: Install ssh key
  tags: 
    - never
    - ssh
  copy:
    src: "./.ssh/id_ed25519"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    mode: 0600

- name: Install ssh key public
  tags:
    - never
    - ssh
  copy:
    src: "./.ssh/id_ed25519.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    mode: 0644

- name: Set authorized key took from file
  tags: 
    - never
    - ssh
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

- name: Install fi ssh key
  tags: 
    - never
    - ssh-fi
  copy:
    src: "./.ssh/id_fi"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_fi"
    mode: 0600

- name: Install fi ssh key public
  tags: 
    - never
    - ssh-fi
  copy:
    src: "./.ssh/id_fi.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_fi.pub"
    mode: 0644

- name: Set fi authorized key took from file
  tags: 
    - never
    - ssh-fi
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_fi.pub') }}"
