- name: Install syncthing
  become: true
  package:
    name: syncthing
    state: present

- name: Start syncthing service
  systemd:
    name: syncthing@thoggard.service
    state: started
    enabled: true
