- name: Install syncthing
  become: true
  package:
    name: syncthing
    state: latest

- name: Start syncthing service
  systemd:
    name: syncthing@thoggard.service
    state: started
    enabled: true

- name: Add syncthing firewall exception

- Add firewall exception to open 8384 for syncthing
