- name: Install tmux
  pacman:
    name: tmux
  become: true

- name: Install tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

      # TODO: I think I have to do something like after installing tmp in order for the TMUX_PLUGIN_MANAGER_PATH to be present
      # - name: Install tmux plugins
      #  shell: "~/.tmux/plugins/tpm/bin/install_plugins"
      #  become_user: thoggard
