- name: Install tmux
  become: true
  package:
    name: tmux
    state: latest

- name: Install tpm
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest:
      "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: Install tmux plugins
  shell: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm/bin/install_plugins"
