# linux
- name: Install todoist
  snap:
    name:
      - todoist
  when:
    - ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Archlinux"
  tags:
    - todoist

# osx
- name: Install todoist
  homebrew:
    name: homebrew/cask/todoist
  when:
    - ansible_facts['os_family'] == "Darwin"
  tags:
    - todoist
